"""add_discount_tables

Revision ID: 0d74dde72587
Revises: 182399b1c510
Create Date: 2025-12-23 11:12:32.240388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d74dde72587'
down_revision: Union[str, Sequence[str], None] = '182399b1c510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ProductSize', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ProductSize', type_='unique')
    # ### end Alembic commands ###
