"""update_product_schema_add_price_season_and_count

Revision ID: 6052261efe2e
Revises: fe1d420f5111
Create Date: 2025-12-20 00:01:11.478479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6052261efe2e'
down_revision: Union[str, Sequence[str], None] = 'fe1d420f5111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'CategoryToDiscount', ['id'])
    op.create_unique_constraint(None, 'ColorToDiscount', ['id'])
    op.create_unique_constraint(None, 'Discount', ['id'])
    op.create_unique_constraint(None, 'Employee', ['id'])
    op.create_unique_constraint(None, 'OrderToSupplier', ['id'])
    op.add_column('Product', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('Product', sa.Column('season', sa.Enum('FALL', 'WINTER', 'SPRING', 'SUMMER', name='Season'), nullable=False))
    op.create_unique_constraint(None, 'Product', ['id'])
    op.create_unique_constraint(None, 'ProductCategory', ['id'])
    op.create_unique_constraint(None, 'ProductColor', ['id'])
    op.drop_column('ProductColor', 'hexCode')
    op.create_unique_constraint(None, 'ProductToDiscount', ['id'])
    op.add_column('ProductToSale', sa.Column('count', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'ProductToSale', ['id'])
    op.create_unique_constraint(None, 'Sale', ['id'])
    op.create_unique_constraint(None, 'SeasonToDiscount', ['id'])
    op.create_unique_constraint(None, 'ShopRest', ['id'])
    op.create_unique_constraint(None, 'SizeToDiscount', ['id'])
    op.create_unique_constraint(None, 'Supplier', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Supplier', type_='unique')
    op.drop_constraint(None, 'SizeToDiscount', type_='unique')
    op.drop_constraint(None, 'ShopRest', type_='unique')
    op.drop_constraint(None, 'SeasonToDiscount', type_='unique')
    op.drop_constraint(None, 'Sale', type_='unique')
    op.drop_constraint(None, 'ProductToSale', type_='unique')
    op.drop_column('ProductToSale', 'count')
    op.drop_constraint(None, 'ProductToDiscount', type_='unique')
    op.add_column('ProductColor', sa.Column('hexCode', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ProductColor', type_='unique')
    op.drop_constraint(None, 'ProductCategory', type_='unique')
    op.drop_constraint(None, 'Product', type_='unique')
    op.drop_column('Product', 'season')
    op.drop_column('Product', 'price')
    op.drop_constraint(None, 'OrderToSupplier', type_='unique')
    op.drop_constraint(None, 'Employee', type_='unique')
    op.drop_constraint(None, 'Discount', type_='unique')
    op.drop_constraint(None, 'ColorToDiscount', type_='unique')
    op.drop_constraint(None, 'CategoryToDiscount', type_='unique')
    # ### end Alembic commands ###
