"""Initial schema

Revision ID: fe1d420f5111
Revises: 
Create Date: 2025-12-19 21:04:43.268368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1d420f5111'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Discount',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Employee',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SELLER', 'ADMIN', name='EmployeeRole'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ProductCategory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imageUrl', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ProductColor',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hexCode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Supplier',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('CategoryToDiscount',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('categoryId', sa.String(), nullable=False),
    sa.Column('discountId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['ProductCategory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discountId'], ['Discount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ColorToDiscount',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('colorId', sa.String(), nullable=False),
    sa.Column('discountId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['colorId'], ['ProductColor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discountId'], ['Discount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Product',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imageUrl', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('colorId', sa.String(), nullable=False),
    sa.Column('categoryId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['ProductCategory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['colorId'], ['ProductColor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Sale',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('finalPrice', sa.Float(), nullable=False),
    sa.Column('employeeId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employeeId'], ['Employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('SeasonToDiscount',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('season', sa.Enum('FALL', 'WINTER', 'SPRING', 'SUMMER', name='Season'), nullable=False),
    sa.Column('discountId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['discountId'], ['Discount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('SizeToDiscount',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('discountId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['discountId'], ['Discount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('OrderToSupplier',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supplierId', sa.String(), nullable=False),
    sa.Column('ProductId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ProductId'], ['Product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplierId'], ['Supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ProductToDiscount',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('discountId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['discountId'], ['Discount.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productId'], ['Product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ProductToSale',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('saleId', sa.String(), nullable=False),
    sa.Column('ProductId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ProductId'], ['Product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saleId'], ['Sale.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ShopRest',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('restCount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('productId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ShopRest')
    op.drop_table('ProductToSale')
    op.drop_table('ProductToDiscount')
    op.drop_table('OrderToSupplier')
    op.drop_table('SizeToDiscount')
    op.drop_table('SeasonToDiscount')
    op.drop_table('Sale')
    op.drop_table('Product')
    op.drop_table('ColorToDiscount')
    op.drop_table('CategoryToDiscount')
    op.drop_table('Supplier')
    op.drop_table('ProductColor')
    op.drop_table('ProductCategory')
    op.drop_table('Employee')
    op.drop_table('Discount')
    # ### end Alembic commands ###
